addSbtPlugin("com.typesafe.play"      %% "sbt-plugin"          % "2.5.13")
addSbtPlugin("org.scala-js"           %% "sbt-scalajs"         % "0.6.14")
addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat"       % "1.0.4")
addSbtPlugin("com.eed3si9n"           %% "sbt-buildinfo"       % "0.6.1")
addSbtPlugin("ch.epfl.scala"          %% "sbt-scalajs-bundler" % "0.9.0")